### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'orig_size'

### ISSUE THREAD

**Issue by anthonylarbalestier** [victordomingos/optimize-images#20]
λ optimize-images /Users/anthony/Downloads/4064VH-PWCopy/4064VH-PW_001.jpg

Using these symbols:

  ✅ Optimized file     ℹ️  EXIF info present
  🔴 Skipped file       ⤵  Image was downsized     🔻 Size reduction (%)

Traceback (most recent call last):
  File "c:\users\anthony\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\anthony\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\anthony\AppData\Local\Programs\Python\Python37-32\Scripts\optimize-images.exe\__main__.py", line 9, in <module>
  File "c:\users\anthony\appdata\local\programs\python\python37-32\lib\site-packages\optimize_images\__main__.py", line 115, in main
    total_src_size = r.orig_size
AttributeError: 'NoneType' object has no attribute 'orig_size'

**Comment by victordomingos** [comment]
Hi,

Thanks for submitting this issue. Is the any additional information you can provide about the error? I’ll leave a few questions that could maybe help us find the bug:

- Which operating system were you using?

- Which version of Pillow do you have installed (`pip list`)?

- Which Python version was optimize-images running on? 

- Which version of optimize-images were you using (`optimize-images -v`)? 

- Did you install from PyPI using `pip`, or did you download directly from GitHub?

- Does this occur just with that specific image file, or did you get a similar trackbacks with other images? 

- Does it happen just with a specific set of command-line arguments (if so, which one?), or it happens always?

**Comment by anthonylarbalestier** [comment]
-

   Which operating system were you using?

Windows 10

   -

   Which version of Pillow do you have installed (pip list)?

  Package               Version
--------------------- ---------
Pillow                6.1.0
pip                   19.2.2

   -

   Which Python version was optimize-images running on?

λ python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32
bit (Intel)] on win32

   -

   Which version of optimize-images were you using (optimize-images -v)?

λ optimize-images -v
1.3.4

   -

   Did you install from PyPI using pip, or did you download directly from
   GitHub?

PyPI

   -

   Does this occur just with that specific image file, or did you get a
   similar trackbacks with other images?

Happened with these images (other images worked fine)
https://schneider-electric.box.com/s/uyj3rimbow8absnaog51n0oykq9lbcsx
uploaded as zip for convenience (I have them extracted)

   -

   Does it happen just with a specific set of command-line arguments (if
   so, which one?), or it happens always?

Always happens with these images, tried using path to optimise the full
folder or individual images

**Comment by victordomingos** [comment]
Thank you very much for your fast and complete answer. Having sample images allowed me to better understand what was happening. Our code had in fact a little bug that would result in an unintended behaviour when the image was not recognised as having one of the supported formats (PNG and JPEG). That partially explains the error you got, and that specific bug is corrected in the version I am submitting very soon. 

The other part of the explanation is that for some reason, Pillow reports the format of those pictures as MPO instead of JPEG. Well, it seems that MPO is an image format based on JPEG, so as of 36dd1526be9637316e066c39200a8d7ebe4d3405 we are now experimentally treating MPO as JPEG files, which means that in case the file has more than one picture in it, only the first one is going to be processed and saved.

The usual disclaimer applies here: ALWAYS make copies before using this tool, since it performs destructive and unrecoverable compression.

I still want do a some tests during the next few days, before submitting this new version (1.3.5) to PyPI.org. If you want to try it sooner, you may download it directly from GitHub and install it [as described in the docs](https://github.com/victordomingos/optimize-images/blob/master/docs/docs_EN.md#installing-the-most-recent-development-version-may-be-unstable).

Please, let me know if this update solved the issue for you.
