### ISSUE TITLE
Brunsli support?

### ISSUE THREAD

**Issue by varnav** [victordomingos/optimize-images#30]
[Brunsli](https://github.com/google/brunsli) is a lossless JPEG repacking library.

Brunsli allows for a 22% decrease in file size while allowing the original JPEG to be recovered byte-by-byte.

Is it possible to add support for it?

**Comment by victordomingos** [comment]
Thanks for your suggestion. It's an interesting development on the JPEG side. However, it falls out of the current scope of this project, given it's approach based on low third-party dependencies. Optimize Images should be available as a pure python application, with just pure python requirements, with the single exception of Pillow. This allows Optimize Images to be compatible with some systems where third-party binaries may not be installed (like Pythonista on iOS).

In order to fulfil this requirement that motivated the development of this application, while not completely banned from the roadmap, any new features that may depend on binary third party dependencies should always be made completely optional. That's what happened recently with watchdog's experimental adoption. 

It may be reconsidered when Pillow adds support for it, however.
