### ISSUE TITLE
Impressive. But what exactly it does to my files?

### ISSUE THREAD

**Issue by varnav** [victordomingos/optimize-images#6]
There is no clear documentation what exactly this script does. If I run it on directory I see impressive optimizations, like twice better than what jpegoptim does, and way faster. But I'm afraid to run it over my photo collection, as I can't understand what it does to images. While it's pretty clear what jpegoptim does.

Can you please clarify in the docs what exactly it does to jpeg files if I run it on directory? Like "if image is bigger that 4000x3000 reduce it to 4000x3000", "strip all EXIF information" "apply lossless optimizations", etc.

**Comment by varnav** [comment]
Sorry, I did not immediately realize that there is a more detailed documentation available here:

https://github.com/victordomingos/optimize-images/blob/master/docs/docs_EN.md

But still description is not completely clear IMO.

**Comment by victordomingos** [comment]
Hi. Thanks for your feedback on the documentation. That is really something I have tried to make as clear as possible, and I can see it can be improved. I am obviously open to suggestions in that field.

First of all, I should say I don’t recommend to run this over your original image files. Most of the operations will have a more or less visible impact on image quality and there is no undo option. Since it has the potential to destroy image files, it is strongly advised to use it only on copies.

Now, about what it does. It is mostly a user level interface to some functionality provided by [Pillow](https://pillow.readthedocs.io/en/stable/). For JPEG images, for instance, it will by default open the file and save it again using a variable JPEG quality setting between 75 and 80 (determined automatically), stripping EXIF data, and using progressive mode if image size is greater than ~10kb. The user may change most of these parameters using the command line arguments.

The current defaults have been chosen with a specific use case in mind, which is image file size reduction for web.

**Comment by varnav** [comment]
Maybe it's worth to have example use for different use case - like I have - optimizing photo library. I made some test runs on my photo library, don't notice any quality loss (I think it's hard to tell the difference between 80 and 90+ quality). But would be great to have more conservative example.
